
name: M-UnitTest_PSD_Test

on:
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:
    inputs:
       logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
       tags:
          description: 'Test scenario tags'

jobs:
  check_date:
    runs-on: PSD
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    - id: should_run
      name: check latest commit is less than a day
      if: ${{ github.event_name == 'schedule' }}
      working-directory: ${{github.workspace}}
      run: 
        date=`date -d "-24 hours" "+%s"`; result=`git rev-list -1 --after=$date main`
        test -z $result && echo "::set-output name=should_run::false"

  Unit_Test:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: PSD
    steps:

    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Build Setup
      working-directory: ${{github.workspace}}
      run: | 
        chmod +x .github/workflows/script/build_setup_165.sh
        .github/workflows/script/build_setup_165.sh -t PSD -r ${{github.sha}} -d ${{github.workspace}}

    - name: Build UT and Run
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/unit/ut_build_run_unittest_psd.sh
        .github/workflows/script/unit/ut_build_run_unittest_psd.sh ${{github.workspace}}

    - name: Copy UT Result to CI Server
      if: always() 
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/unit/copy_ut_result.sh
        .github/workflows/script/unit/copy_ut_result.sh ${{github.workspace}} ${{github.sha}}

    - name: Copy gcov report back to CI server
      if: always() 
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/unit/copy_gcov_report.sh
        .github/workflows/script/unit/copy_gcov_report.sh ${{github.workspace}}

    - uses: mikepenz/action-junit-report@v2
      if: always() 
      with:
        report_paths: 'UnitTestResult/*.xml'
